version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: devDB123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - proydev_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@proydev.com
      PGADMIN_DEFAULT_PASSWORD: devPG123
    ports:
      - "8080:80"
    networks:
      - proydev_network

networks:
  proydev_network:
    driver: bridge